### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by alex5nader** [acmutd/nebula-web#39]
Currently, Nebula has no license. This means that all code contributed to the project is All Rights Reserved to the contributors who contributed it, and cannot be redistributed or modified without explicit permission. Though I doubt anyone in ACM would hold the project hostage, having a proper license will prevent any external contributors from doing so. See more information here: https://choosealicense.com/no-permission/.

I would recommend using the AGPL v3.0 or later, which allows anyone to redistribute and modify Nebula, but requires that anyone who does so provide a license and copyright notice, disclose their modified source, and also license the derived work under the AGPL. The AGPL also considers network use to be redistribution, which would prevent anyone from taking code from Nebula and using it to providing a service which is not open source.

If requiring derived works to license under AGPL is too restrictive, the MIT License is another good choice. It also allows anyone to redistribute and modify Nebula, and requires a license and copyright notice to be distributed with the derived work. However, it does not restrict the license of the derived work or require the derived work's source to be disclosed.

Additionally, there are many more licenses detailed here, if the AGPL or MIT License do not seem right for the project: https://choosealicense.com/licenses/.

Please also note that re-licensing a project (or choosing an initial one) technically requires explicit permission from all past contributors.

**Comment by WillieCubed** [comment]
Hey there, thank you for bringing this to our attention!

This was an oversight. The license we've chosen (the MIT license) is already in a development branch of the project (PR #37), but it has yet to be pushed to the main branch pending a final decision from our existing contributors.

We look forward to future contributors to the project!

**Comment by WillieCubed** [comment]
Once again, thank you for bringing this up. All Project Nebula repositories will use the MIT license, and this repository has been updated to reflect that (commit 39feb6751372cc8bef0fe4adbb15fa8f4b554ddf).

If you have any other questions, see the contributor's [guide](https://github.com/acmutd/nebula-web/blob/develop/CONTRIBUTING.md). There are going to be a lot more commits in the coming week. ;)
