### ISSUE TITLE
[Feature Request] Allow a user to import a degree plan from file

### ISSUE THREAD

**Issue by WillieCubed** [acmutd/nebula-web#48]
# Overview

When #47 is implemented, we will have the ability to export degree plans to files, but that's no use if we can't use the machine-readable format. A user must be able to import a course plan and have it replace their currently active plan or create another plan that displays in their plan list.

# Proposal

- [x] Allow a user to select a plan from file
- [x] Replace the currently active plan in the planner UI
- [ ] Give the option to create a new plan that shows up in a user's degree plan list

## Supplementary Information

At some point, we will have to consider how to handle data syncing, namely whether or not to outright replace the currently loaded plan or to use some more sophisticated conflict resolution strategy, like only overriding future semesters based on an imported plan.

@wbne, how do you think we can handle this?

**Comment by wbne** [comment]
I would imagine a user would expect the uploaded file to overwrite the data on the website.
I think as long as we have a specific format that the user follows we can assume anything within the file will overwrite the website.
Eg. If a user uploads a file with classes for year 3 and 4, we would overwrite the website data with the new years 3 and 4

**Comment by WillieCubed** [comment]
The exported plan will consist of a student's entire degree plan (all courses for all semesters), so I support overwriting the file for now and later giving an option in the import screen to specify import options like overwriting all semesters or just future semesters or creating a new plan instance.
